###################  spring配置  ###################
spring:
  # 数据库配置
  datasource:
#    url: jdbc:mysql://58.221.49.26:3306/byb_csdn?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2b8
#    username: root
#    password: root
    url: jdbc:mysql://192.168.10.94:3306/haulage_motor?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2b8&serverTimezone=GMT%2b8
    username: root
    password: bYb123456.
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-active: 50
      initial-size: 1
      max-wait: 60000
      min-idle: 20
      remove-abandoned: true
      remove-abandoned-timeout: 600
      connection-properties: clientEncoding=UTF-8
  main:
    allow-bean-definition-overriding: true
  mvc:
    async:
      #接口请求时长。超过20s丢弃
      request-timeout: 20000
    favicon:
      enabled: false
################### redis 配置 ###################
  redis:
    host: 127.0.0.1
    port: 6379
    password: ''
    jedis:
      pool:
        max-active: 30
        max-wait: 100
        max-idle: 30
        min-idle: 5
    timeout: 6000
    # 0-15
    database: 0
  cache:
    packages: com.zhuzhou.spi
  # spring-session 配置
  session:
    store-type: redis
    timeout: 1800
  servlet:
    multipart:
      max-request-size: 10000MB
      max-file-size: 10000MB
      location: D:/tempfile
###################  mybatis配置  ###################
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.zhuzhou.entity, com.zhuzhou.form, com.zhuzhou.bo, com.zhuzhou.vo
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
# 打印sql
logging:
  level:
    com.zhuzhou.dao: DEBUG
    com.zhuzhou.service: INFO
    com.zhuzhou.controller: INFO
  file: D:\log\haulage_motor
server:
  port: 8300
  tomcat:
    # 最大连接数
    max-connections: 200
    max-threads: 1024
  #设置连接时间
  servlet:
    session:
      #一天
      timeout: P1D
############### 基本信息配置 ####################
url:
  idx: 'http://192.168.10.104:6002/api/Parse/Idx'
  lkj: 'http://192.168.10.104:6002/api/Parse/LKJ'
file:
  source: D:\zhuzhou\source\haulage_motor
  hand: D:\zhuzhou\hand
  cover: D:\zhuzhou\cover
  machineroom: D:\zhuzhou\machineroom
  #decode: D:\zhuzhou\decode\haulage_motor
  uri: 'http://192.168.10.127:${server.port}'
  pool:
    size: 10